"""Aegisub 兼容的 k-tag ASS 生成器。

关键约束：
- 一句一个源 Dialogue，字/词前写标准 ASS karaoke 标签 ``\\k`` / ``\\kf`` / ``\\ko``；
- Aegisub Karaoke Templater 的模板必须是 ``[Events]`` 中 Effect 为
  ``template syl ...`` 的 Comment 事件，不能写进 ``[Aegisub Project Garbage]``；
- k-tag 是相对行起点的累计时长。本实现按字的绝对起点重新量化到厘秒，
  把字间静音计入前一字，从而避免旧实现忽略字间空隙后逐字漂移。
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import List, Literal

from .ass_style import AssStylePrefs
from .ass_utils import escape_ass_text, sanitize_ass_field
from .converter import WordHighlightStyle, _filter_animation_words
from .karaoke_template import KaraokeTemplatePrefs, default_karaoke_templates
from .media_types import VIDEO_SUFFIXES
from .models import Sentence, WordTimestamp
from .time_fmt import ass_time


KMode = Literal["kf", "K", "k", "ko"]
_VALID_K_MODES = {"kf", "K", "k", "ko"}


@dataclass
class AssKaraokeHeader:
    """旧 API 的兼容头部；新 UI 优先传 AssStylePrefs。"""

    title: str = "Untitled"
    play_res_x: int = 1920
    play_res_y: int = 1080
    wrap_style: int = 2
    font_name: str = "Source Han Sans SC Bold"
    font_size: int = 64
    primary_colour: str = "&H00FFFFFF"
    outline_colour: str = "&H00000000"
    back_colour: str = "&H00000000"
    bold: bool = True
    italic: bool = False
    outline: int = 3
    shadow: int = 2
    alignment: int = 2


def _script_info_block(h: AssKaraokeHeader) -> str:
    return "\n".join([
        "[Script Info]",
        "; Script generated by Qwen3-Subtitle-Studio (Aegisub karaoke source)",
        f"Title: {sanitize_ass_field(h.title, fallback='Untitled')}",
        "ScriptType: v4.00+",
        "Collisions: Normal",
        f"PlayResX: {h.play_res_x}",
        f"PlayResY: {h.play_res_y}",
        f"WrapStyle: {h.wrap_style}",
        "ScaledBorderAndShadow: yes",
        "YCbCr Matrix: TV.709",
        "",
    ])


def _script_info_from_ass_style(st: AssStylePrefs, *, title: str = "Untitled") -> str:
    return "\n".join([
        "[Script Info]",
        "; Script generated by Qwen3-Subtitle-Studio (Aegisub karaoke source)",
        f"Title: {sanitize_ass_field(title, fallback='Untitled')}",
        "ScriptType: v4.00+",
        "Collisions: Normal",
        f"PlayResX: {st.play_res_x}",
        f"PlayResY: {st.play_res_y}",
        f"WrapStyle: {st.wrap_style}",
        "ScaledBorderAndShadow: yes",
        "YCbCr Matrix: TV.709",
        "",
    ])


def _aegisub_media_path(value: str | Path | None) -> str:
    if not value:
        return ""
    path = Path(value).expanduser()
    try:
        path = path.resolve(strict=False)
    except OSError:
        pass
    return str(path).replace("\r", " ").replace("\n", " ")


def _aegisub_garbage_block(
    *,
    source_media_path: str | Path | None = None,
    audio_path: str | Path | None = None,
    video_path: str | Path | None = None,
) -> str:
    """Aegisub 项目元数据；优先写入用户原媒体绝对路径。"""
    source = _aegisub_media_path(source_media_path)
    video = _aegisub_media_path(video_path)
    if not video and source and Path(source).suffix.lower() in VIDEO_SUFFIXES:
        video = source
    # 视频的音轨直接从原视频读取，避免把会被龄期清理的 .temp 提取件写进 ASS。
    audio = video or source or _aegisub_media_path(audio_path)
    video_value = video or "?dummy:23.976000:40000:1920:1080:27:163:204:255:c:"
    keyframes = "?video" if video else ""
    return "\n".join([
        "[Aegisub Project Garbage]",
        "Last Style Storage: Default",
        f"Audio File: {audio}",
        f"Video File: {video_value}",
        f"Keyframes File: {keyframes}",
        "Video AR Mode: 4",
        "Video AR Value: 1.777778",
        "Video Zoom Percent: 0.750000",
        "",
    ])


def _styles_block_from_header(h: AssKaraokeHeader) -> str:
    bold_flag = -1 if h.bold else 0
    italic_flag = -1 if h.italic else 0
    fmt = (
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, "
        "Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
        "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
    )
    default_style = (
        "Style: Default,{fn},{fs},{pc},&H000000FF,{oc},{bc},"
        "{b},{i},0,0,100,100,0,0,1,{ol},{sh},{al},120,120,60,1"
    ).format(
        fn=sanitize_ass_field(h.font_name, fallback="Arial"), fs=h.font_size, pc=h.primary_colour,
        oc=h.outline_colour, bc=h.back_colour, b=bold_flag, i=italic_flag,
        ol=h.outline, sh=h.shadow, al=h.alignment,
    )
    return "\n".join(["[V4+ Styles]", fmt, default_style, ""])


def _normalize_k_mode(mode: str) -> KMode:
    # 旧版 UI 曾提供不存在于 ASS/Aegisub 标准中的 \km；读取旧 preferences 时
    # 自动迁移为语义最接近的离散高亮 \k。
    if mode == "km":
        return "k"
    if mode not in _VALID_K_MODES:
        raise ValueError(f"unsupported ASS karaoke tag: {mode!r}; use 'kf', 'K', 'k' or 'ko'")
    return mode  # type: ignore[return-value]


def _animation_words(sentence: Sentence, style: WordHighlightStyle) -> list[WordTimestamp]:
    # 标点/空白保留在 sentence.text 中，但不生成独立 k-tag。
    return _filter_animation_words(list(sentence.words or []))


def _locate_words(sentence_text: str, words: list[WordTimestamp]) -> list[tuple[int, int]]:
    """按顺序在原句中定位字/词；找不到时做不越界的顺序降级。"""
    positions: list[tuple[int, int]] = []
    cursor = 0
    for word in words:
        pos = sentence_text.find(word.text, cursor)
        if pos < 0:
            pos = min(cursor, len(sentence_text))
        end = min(len(sentence_text), pos + len(word.text))
        positions.append((pos, end))
        cursor = end
    return positions


def build_karaoke_line_text(
    sentence: Sentence,
    *,
    k_mode: KMode = "kf",
    style: WordHighlightStyle | None = None,
) -> str:
    """把一句转成 Aegisub 可识别的标准 k-tag 源行。

    每个标签的开始时刻由 ``word.start_time - sentence.start_time`` 决定；
    标签时长延伸到下一个字开始，最后一个延伸到句尾，因此所有 k 时长之和
    与 Dialogue 时长（厘秒量化后）一致。显式标点不会单独高亮，但会保留在
    相邻 k-tag 之间，文本不会丢失。
    """
    if not sentence.has_word_level():
        raise ValueError(
            "k-tag ASS requires word-level timestamps on every sentence; "
            "sentence.text=" + repr(sentence.text[:24])
        )
    mode = _normalize_k_mode(str(k_mode))
    st = style or WordHighlightStyle()
    words = _animation_words(sentence, st)
    if not words:
        total_cs = max(0, int(round(sentence.duration * 100)))
        return "{\\%s%d}%s" % (mode, total_cs, escape_ass_text(sentence.text))

    positions = _locate_words(sentence.text, words)
    total_cs = max(0, int(round(sentence.duration * 100)))

    # 绝对起点一次性量化，避免逐字 round 后累计误差。
    starts: list[int] = []
    previous = 0
    for word in words:
        value = int(round((word.start_time - sentence.start_time) * 100))
        value = max(previous, min(total_cs, value))
        starts.append(value)
        previous = value

    parts: list[str] = []
    cursor = 0
    first_start = starts[0]
    first_pos = positions[0][0]
    prefix = sentence.text[:first_pos]
    if first_start > 0 or prefix:
        # 空白/前置标点作为 0/前导时长的非动画 syllable，Templater 可正常解析。
        parts.append("{\\%s%d}%s" % (mode, first_start, escape_ass_text(prefix)))
        cursor = first_pos

    for i, (word, (pos, end)) in enumerate(zip(words, positions)):
        # 位于两个 animation word 之间的显式标点，归入前一个 syllable 的文本。
        if pos > cursor:
            parts.append(escape_ass_text(sentence.text[cursor:pos]))
        next_start = starts[i + 1] if i + 1 < len(starts) else total_cs
        duration_cs = max(0, next_start - starts[i])
        visible = sentence.text[pos:end] or word.text
        parts.append("{\\%s%d}%s" % (mode, duration_cs, escape_ass_text(visible)))
        cursor = end

    if cursor < len(sentence.text):
        parts.append(escape_ass_text(sentence.text[cursor:]))
    return "".join(parts)


def _automation_template_lines(
    style_name: str,
    template_prefs: "KaraokeTemplatePrefs | None" = None,
) -> list[str]:
    """Karaoke Templater 可直接识别的事件模板。

    模板内容由 subs.karaoke_template 的 KaraokeTemplatePrefs 渲染。未传偏好时
    使用默认首选；用户明确全不选时返回空，不附加 Automation Comment。
    用户可在 Aegisub 中编辑/复制这些 Comment，再运行
    Automation → Apply karaoke template。
    """
    prefs = template_prefs or default_karaoke_templates()
    return prefs.render_comments(style_name)


def build_events(
    sentences: List[Sentence],
    *,
    k_mode: KMode = "kf",
    style: WordHighlightStyle | None = None,
    default_style_name: str = "Default",
    layer: int = 0,
    include_automation_template: bool = True,
    template_prefs: "KaraokeTemplatePrefs | None" = None,
) -> str:
    mode = _normalize_k_mode(str(k_mode))
    default_style_name = sanitize_ass_field(default_style_name, fallback="Default")
    lines: list[str] = [
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]
    if include_automation_template:
        lines.extend(_automation_template_lines(default_style_name, template_prefs))
    for sentence in sentences:
        text = build_karaoke_line_text(sentence, k_mode=mode, style=style)
        style_name = sanitize_ass_field(sentence.ass_style, fallback=default_style_name)
        lines.append(
            # 标准“尚未套模板”的 timed karaoke 源行：Dialogue + 空 Effect。
            # Aegisub 应用模板后会自动把源行改成 Comment/effect=karaoke。
            "Dialogue: {layer},{start},{end},{style},{name},0000,0000,0000,,{text}".format(
                layer=layer,
                start=ass_time(sentence.start_time),
                end=ass_time(sentence.end_time),
                style=style_name,
                name=sanitize_ass_field(sentence.speaker),
                text=text,
            )
        )
    lines.append("")
    return "\n".join(lines)


def build_ass_document(
    sentences: List[Sentence],
    *,
    header: AssKaraokeHeader | None = None,
    k_mode: KMode = "kf",
    include_aegisub_garbage: bool = True,
    include_automation_template: bool = True,
    style: WordHighlightStyle | None = None,
    ass_style: AssStylePrefs | None = None,
    template_prefs: "KaraokeTemplatePrefs | None" = None,
    source_media_path: str | Path | None = None,
    audio_path: str | Path | None = None,
    video_path: str | Path | None = None,
) -> str:
    """构建 Aegisub timed-karaoke 源。

    默认附带可运行的示例模板，使 Aegisub 打开后能直接 Apply karaoke template；
    模板是 Comment，PotPlayer/ASS renderer 会忽略它，不影响直接播放。
    """
    parts: list[str] = []
    if ass_style is not None:
        parts.append(_script_info_from_ass_style(ass_style))
        parts.append(ass_style.render_styles_block())
        default_style_name = ass_style.name
    else:
        h = header or AssKaraokeHeader()
        parts.append(_script_info_block(h))
        parts.append(_styles_block_from_header(h))
        default_style_name = "Default"
    if include_aegisub_garbage:
        parts.append(_aegisub_garbage_block(
            source_media_path=source_media_path,
            audio_path=audio_path,
            video_path=video_path,
        ))
    parts.append(build_events(
        sentences,
        k_mode=k_mode,
        style=style,
        default_style_name=default_style_name,
        include_automation_template=include_automation_template,
        template_prefs=template_prefs,
    ))
    return "\n".join(parts).rstrip() + "\n"


__all__ = [
    "KMode", "AssKaraokeHeader", "build_karaoke_line_text", "build_events",
    "build_ass_document",
]
